### ISSUE TITLE
[BUG] - Navbar-Mobile-bug

### ISSUE THREAD

**Issue by tomsabu444** [tomsabu444/Pala-Marathon-Website#98]
**Description**  
The navbar's menu button on mobile devices (iOS and Android) redirects successfully, but it does not close after being clicked. Additionally, the clock button and its dropdown menu do not close. This issue is limited to mobile devices and affects all browsers. The desktop view functions correctly.

---

**Steps to Reproduce**  
1. **Step 1**: Open the website on a mobile device (iOS or Android).  
2. **Step 2**: Click on the navbar menu button.  
3. **Step 3**: Observe that the menu redirects to the correct location, but the backdrop remains, and the menu does not close.  
4. **Step 4**: Try interacting with the close button or its dropdown menu.  
5. **Result**: The navbar menu and the close button/dropdown do not close as expected, leaving the backdrop visible.

---

**Expected Behavior**  
- Clicking the navbar menu button should close the menu after redirecting.  
- The backdrop should disappear.  
- The close button and its dropdown should close when interacted with.  

---
**Video**  

https://github.com/user-attachments/assets/9625fd5f-ac1c-4390-8103-3e3ab62ec6b6

---

**Environment**  
- **OS**: iOS and Android  
- **Browser**: Chrome, Safari, and other mobile browsers  

---

**Additional Context**  
- This issue affects all tested mobile browsers on iOS and Android.  
- Desktop view works as intended without any issues.  
- The inability to close the menu and clock button disrupts the user experience.

**Comment by suraijmuhammed** [comment]
https://github.com/user-attachments/assets/c179e114-6350-40df-bb9c-095d54ffdfa7

I couldnt able to find issue in my branch
